name: Build

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:

  build-macos:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
    - name: Build
      run: |
        git config --global user.email "builds@travis-ci.com"
        git config --global user.name "Travis CI"
        brew install autoconf automake libtool
        mkdir build
        cd build
        cmake ..
        make -j$(nproc) tarball
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: vitasdk-macos
        path: build/*.tar.bz2

